# Mount Drive

In [61]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Import Libraries

In [62]:
#Load the required libraries

import os

import pandas as pd
from datetime import datetime

# Import Data

## BTC

In [63]:
# Importing one csv file
pd.read_csv("/content/drive/MyDrive/Colab Notebooks/01 Omdena/Bahrain - Crypto/Project_Data/binance/BTCUSDT/BTCUSDT-1h-2019-09.csv", header=None)

,0,1,2,3,4,5,6,7,8,9,10,11
0,1567296000000,9588.74,9630.00,9579.34,9617.06,546.960415,1567299599999,5.257943e+06,7428,261.131656,2.510480e+06,0
1,1567299600000,9617.06,9642.58,9612.08,9614.99,453.105152,1567303199999,4.362498e+06,5789,258.764082,2.491295e+06,0
2,1567303200000,9614.99,9616.00,9595.76,9605.78,458.004517,1567306799999,4.400751e+06,5485,321.355630,3.088171e+06,0
3,1567306800000,9606.12,9624.01,9605.78,9623.02,633.588749,1567310399999,6.092024e+06,5500,446.853542,4.296649e+06,0
4,1567310400000,9623.02,9630.21,9605.60,9614.46,542.260896,1567313999999,5.216076e+06,5536,368.470786,3.544535e+06,0
...,...,...,...,...,...,...,...,...,...,...,...,...
715,1569870000000,8259.74,8274.00,8232.35,8269.53,722.491425,1569873599999,5.958969e+06,9268,400.933356,3.306980e+06,0
716,1569873600000,8269.34,8275.00,8163.36,8214.67,2141.971340,1569877199999,1.757720e+07,16271,986.290265,8.088017e+06,0
717,1569877200000,8213.46,8270.00,8171.00,8233.45,1037.885174,1569880799999,8.520877e+06,12483,579.799417,4.760217e+06,0
718,1569880800000,8233.49,8273.55,8201.00,8218.58,833.452074,1569884399999,6.863412e+06,9788,437.053045,3.599664e+06,0
719,1569884400000,8219.33,8295.00,8217.93,8289.34,954.147243,1569887999999,7.877128e+06,11012,600.969720,4.960848e+06,0

According to binance these are the columns from the csv files:

- open_time: Kline Open time in unix time format

- open: Open Price

- high: High Price

- low: Low Price

- close: Close Price

- volume: Volume

- close_time: Kline Close time in unix time format

- quote_volume: Quote Asset Volume

- count: Number of Trades

- taker_buy_volume: Taker buy quote asset volume during this period

- taker_buy_quote_volume: Taker buy base asset volume during this period

- ignore : Ignore(youcan drop this feature)

In [64]:
# Create a list of the files

folder_path_BTC = '/content/drive/MyDrive/Colab Notebooks/01 Omdena/Bahrain - Crypto/Project_Data/binance/BTCUSDT'

file_list_BTC = os.listdir(folder_path_BTC)

In [65]:
# Merging all files

dfs_BTC = []

for i in file_list_BTC:
  dfs_BTC.append(pd.read_csv(f"/content/drive/MyDrive/Colab Notebooks/01 Omdena/Bahrain - Crypto/Project_Data/binance/BTCUSDT/{i}", header=None))

# Concatenate all data into one DataFrame
data_BTC = pd.concat(dfs_BTC, ignore_index=True)

data_BTC.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,1596240000000,11335.46,11389.00,11220.00,11248.35,3192.171488,1596243599999,3.604980e+07,45488,1260.669609,1.423339e+07,0
1,1596243600000,11247.86,11303.03,11226.23,11266.97,1685.735081,1596247199999,1.900689e+07,27094,697.954037,7.869257e+06,0
2,1596247200000,11266.97,11345.32,11258.71,11334.81,2095.667551,1596250799999,2.370859e+07,32541,713.287526,8.068543e+06,0
3,1596250800000,11334.91,11405.93,11318.59,11366.16,2687.160709,1596254399999,3.054698e+07,33852,1171.927418,1.332533e+07,0
4,1596254400000,11366.16,11428.05,11335.00,11388.21,3062.946602,1596257999999,3.488974e+07,40180,1318.771157,1.502381e+07,0

In [66]:
data_BTC.shape

(32821, 12)

In [67]:
# Renaming the columns

data_BTC.columns = [
    'open_time',
    'open',
    'high',
    'low',
    'close',
    'volume',
    'close_time',
    'quote_volume',
    'count',
    'taker_buy_volume',
    'taker_buy_quote_volume',
    'ignore'
]

In [68]:
# Removing ignore column

data_BTC.drop(labels="ignore", axis=1, inplace=True)

In [69]:
# Changing to datetime

data_BTC["open_time"] = pd.to_datetime(data_BTC["open_time"], origin='unix',unit='ms')
data_BTC["close_time"] = pd.to_datetime(data_BTC["close_time"], origin='unix',unit='ms')

In [70]:
data_BTC.head()

,open_time,open,high,low,close,volume,close_time,quote_volume,count,taker_buy_volume,taker_buy_quote_volume
0,2020-08-01 00:00:00,11335.46,11389.00,11220.00,11248.35,3192.171488,2020-08-01 00:59:59.999,3.604980e+07,45488,1260.669609,1.423339e+07
1,2020-08-01 01:00:00,11247.86,11303.03,11226.23,11266.97,1685.735081,2020-08-01 01:59:59.999,1.900689e+07,27094,697.954037,7.869257e+06
2,2020-08-01 02:00:00,11266.97,11345.32,11258.71,11334.81,2095.667551,2020-08-01 02:59:59.999,2.370859e+07,32541,713.287526,8.068543e+06
3,2020-08-01 03:00:00,11334.91,11405.93,11318.59,11366.16,2687.160709,2020-08-01 03:59:59.999,3.054698e+07,33852,1171.927418,1.332533e+07
4,2020-08-01 04:00:00,11366.16,11428.05,11335.00,11388.21,3062.946602,2020-08-01 04:59:59.999,3.488974e+07,40180,1318.771157,1.502381e+07

In [71]:
# Sorting Ascending

data_BTC.sort_values(by = "open_time", ascending=True, inplace=True)

In [72]:
data_BTC.head()

,open_time,open,high,low,close,volume,close_time,quote_volume,count,taker_buy_volume,taker_buy_quote_volume
19007,2019-09-01 00:00:00,9588.74,9630.00,9579.34,9617.06,546.960415,2019-09-01 00:59:59.999,5.257943e+06,7428,261.131656,2.510480e+06
19008,2019-09-01 01:00:00,9617.06,9642.58,9612.08,9614.99,453.105152,2019-09-01 01:59:59.999,4.362498e+06,5789,258.764082,2.491295e+06
19009,2019-09-01 02:00:00,9614.99,9616.00,9595.76,9605.78,458.004517,2019-09-01 02:59:59.999,4.400751e+06,5485,321.355630,3.088171e+06
19010,2019-09-01 03:00:00,9606.12,9624.01,9605.78,9623.02,633.588749,2019-09-01 03:59:59.999,6.092024e+06,5500,446.853542,4.296649e+06
19011,2019-09-01 04:00:00,9623.02,9630.21,9605.60,9614.46,542.260896,2019-09-01 04:59:59.999,5.216076e+06,5536,368.470786,3.544535e+06

In [73]:
data_BTC.tail()

,open_time,open,high,low,close,volume,close_time,quote_volume,count,taker_buy_volume,taker_buy_quote_volume
6554,2023-05-31 19:00:00,27037.06,27123.43,27000.20,27010.57,1064.24189,2023-05-31 19:59:59.999,2.879819e+07,28990,482.38594,1.305342e+07
6555,2023-05-31 20:00:00,27010.57,27116.13,27005.16,27114.20,835.43916,2023-05-31 20:59:59.999,2.262138e+07,22409,440.84291,1.193703e+07
6556,2023-05-31 21:00:00,27114.19,27119.77,27045.61,27090.79,644.01902,2023-05-31 21:59:59.999,1.744376e+07,19452,254.03940,6.879695e+06
6557,2023-05-31 22:00:00,27090.78,27193.24,27084.92,27183.98,999.11868,2023-05-31 22:59:59.999,2.711602e+07,26045,517.76569,1.405207e+07
6558,2023-05-31 23:00:00,27183.97,27299.99,27159.63,27210.35,1483.72375,2023-05-31 23:59:59.999,4.038319e+07,32891,687.67958,1.871858e+07

In [74]:
data_BTC.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32821 entries, 19007 to 6558
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   open_time               32821 non-null  datetime64[ns]
 1   open                    32821 non-null  float64
 2   high                    32821 non-null  float64
 3   low                     32821 non-null  float64
 4   close                   32821 non-null  float64
 5   volume                  32821 non-null  float64
 6   close_time              32821 non-null  datetime64[ns]
 7   quote_volume            32821 non-null  float64
 8   count                   32821 non-null  int64
 9   taker_buy_volume        32821 non-null  float64
 10  taker_buy_quote_volume  32821 non-null  float64
dtypes: datetime64[ns](2), float64(8), int64(1)
memory usage: 3.0 MB

In [75]:
# Saving BTC merged file

data_BTC.to_csv("/content/drive/MyDrive/Colab Notebooks/01 Omdena/Bahrain - Crypto/Project_Data/binance/BTCUSDT_merged.csv", index=False)

In [76]:
pd.read_csv("/content/drive/MyDrive/Colab Notebooks/01 Omdena/Bahrain - Crypto/Project_Data/binance/BTCUSDT_merged.csv")

,open_time,open,high,low,close,volume,close_time,quote_volume,count,taker_buy_volume,taker_buy_quote_volume
0,2019-09-01 00:00:00,9588.74,9630.00,9579.34,9617.06,546.960415,2019-09-01 00:59:59.999,5.257943e+06,7428,261.131656,2.510480e+06
1,2019-09-01 01:00:00,9617.06,9642.58,9612.08,9614.99,453.105152,2019-09-01 01:59:59.999,4.362498e+06,5789,258.764082,2.491295e+06
2,2019-09-01 02:00:00,9614.99,9616.00,9595.76,9605.78,458.004517,2019-09-01 02:59:59.999,4.400751e+06,5485,321.355630,3.088171e+06
3,2019-09-01 03:00:00,9606.12,9624.01,9605.78,9623.02,633.588749,2019-09-01 03:59:59.999,6.092024e+06,5500,446.853542,4.296649e+06
4,2019-09-01 04:00:00,9623.02,9630.21,9605.60,9614.46,542.260896,2019-09-01 04:59:59.999,5.216076e+06,5536,368.470786,3.544535e+06
...,...,...,...,...,...,...,...,...,...,...,...
32816,2023-05-31 19:00:00,27037.06,27123.43,27000.20,27010.57,1064.241890,2023-05-31 19:59:59.999,2.879819e+07,28990,482.385940,1.305342e+07
32817,2023-05-31 20:00:00,27010.57,27116.13,27005.16,27114.20,835.439160,2023-05-31 20:59:59.999,2.262138e+07,22409,440.842910,1.193703e+07
32818,2023-05-31 21:00:00,27114.19,27119.77,27045.61,27090.79,644.019020,2023-05-31 21:59:59.999,1.744376e+07,19452,254.039400,6.879695e+06
32819,2023-05-31 22:00:00,27090.78,27193.24,27084.92,27183.98,999.118680,2023-05-31 22:59:59.999,2.711602e+07,26045,517.765690,1.405207e+07
32820,2023-05-31 23:00:00,27183.97,27299.99,27159.63,27210.35,1483.723750,2023-05-31 23:59:59.999,4.038319e+07,32891,687.679580,1.871858e+07

## ETH

In [77]:
# Importing one csv file

pd.read_csv("/content/drive/MyDrive/Colab Notebooks/01 Omdena/Bahrain - Crypto/Project_Data/binance/ETHUSDT/ETHUSDT-1h-2019-09.csv", header=None)

,0,1,2,3,4,5,6,7,8,9,10,11
0,1567296000000,171.52,172.89,171.36,172.45,5981.16399,1567299599999,1.030126e+06,3753,3576.32332,6.158866e+05,0
1,1567299600000,172.47,173.42,172.41,172.71,7929.54701,1567303199999,1.372183e+06,3310,5532.93656,9.573012e+05,0
2,1567303200000,172.67,172.97,172.02,172.43,2650.04457,1567306799999,4.568114e+05,2666,1333.25886,2.298529e+05,0
3,1567306800000,172.41,172.83,172.32,172.57,2676.49085,1567310399999,4.618308e+05,2612,1445.60395,2.494501e+05,0
4,1567310400000,172.50,172.74,172.11,172.46,2596.85893,1567313999999,4.476401e+05,2848,1524.31952,2.627826e+05,0
...,...,...,...,...,...,...,...,...,...,...,...,...
715,1569870000000,177.46,177.82,176.84,177.80,8272.43721,1569873599999,1.467116e+06,3163,3943.74366,6.996952e+05,0
716,1569873600000,177.80,177.94,175.20,176.39,19274.90520,1569877199999,3.397738e+06,6184,8232.42180,1.451098e+06,0
717,1569877200000,176.46,177.50,176.14,177.25,9982.61979,1569880799999,1.764286e+06,4123,5841.56746,1.032453e+06,0
718,1569880800000,177.26,178.55,176.92,177.03,9205.65198,1569884399999,1.634921e+06,4065,4631.25047,8.228405e+05,0
719,1569884400000,177.04,181.24,177.02,180.85,23746.34438,1569887999999,4.256066e+06,6625,11498.78472,2.063193e+06,0

In [78]:
# Create a list of the files

folder_path_ETH = '/content/drive/MyDrive/Colab Notebooks/01 Omdena/Bahrain - Crypto/Project_Data/binance/ETHUSDT'

file_list_ETH = os.listdir(folder_path_ETH)

In [79]:
# Merging all files

dfs_ETH = []

for i in file_list_ETH:
  dfs_ETH.append(pd.read_csv(f"/content/drive/MyDrive/Colab Notebooks/01 Omdena/Bahrain - Crypto/Project_Data/binance/ETHUSDT/{i}", header=None))

# Concatenate all data into one DataFrame
data_ETH = pd.concat(dfs_ETH, ignore_index=True)

data_ETH.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,1596240000000,346.32,347.77,343.50,344.01,32129.07805,1596243599999,1.109512e+07,15436,15001.14181,5.180064e+06,0
1,1596243600000,344.02,346.36,343.07,345.22,15003.06970,1596247199999,5.177087e+06,8651,7115.68748,2.455421e+06,0
2,1596247200000,345.22,348.00,344.83,346.65,39598.90096,1596250799999,1.373585e+07,14115,22571.56330,7.828799e+06,0
3,1596250800000,346.64,352.85,346.12,352.26,74961.98767,1596254399999,2.626809e+07,27160,47858.69233,1.676916e+07,0
4,1596254400000,352.26,355.13,350.50,353.82,52029.92308,1596257999999,1.836246e+07,22855,27576.79013,9.734660e+06,0

In [80]:
data_ETH.shape

(32821, 12)

In [81]:
# Renaming the columns

data_ETH.columns = [
    'open_time',
    'open',
    'high',
    'low',
    'close',
    'volume',
    'close_time',
    'quote_volume',
    'count',
    'taker_buy_volume',
    'taker_buy_quote_volume',
    'ignore'
]

In [82]:
# Removing ignore column

data_ETH.drop(labels="ignore", axis=1, inplace=True)

In [83]:
# Changing to datetime

data_ETH["open_time"] = pd.to_datetime(data_ETH["open_time"], origin='unix',unit='ms')
data_ETH["close_time"] = pd.to_datetime(data_ETH["close_time"], origin='unix',unit='ms')

In [84]:
data_ETH.head()

,open_time,open,high,low,close,volume,close_time,quote_volume,count,taker_buy_volume,taker_buy_quote_volume
0,2020-08-01 00:00:00,346.32,347.77,343.50,344.01,32129.07805,2020-08-01 00:59:59.999,1.109512e+07,15436,15001.14181,5.180064e+06
1,2020-08-01 01:00:00,344.02,346.36,343.07,345.22,15003.06970,2020-08-01 01:59:59.999,5.177087e+06,8651,7115.68748,2.455421e+06
2,2020-08-01 02:00:00,345.22,348.00,344.83,346.65,39598.90096,2020-08-01 02:59:59.999,1.373585e+07,14115,22571.56330,7.828799e+06
3,2020-08-01 03:00:00,346.64,352.85,346.12,352.26,74961.98767,2020-08-01 03:59:59.999,2.626809e+07,27160,47858.69233,1.676916e+07
4,2020-08-01 04:00:00,352.26,355.13,350.50,353.82,52029.92308,2020-08-01 04:59:59.999,1.836246e+07,22855,27576.79013,9.734660e+06

In [85]:
# Sorting Ascending

data_ETH.sort_values(by = "open_time", ascending=True, inplace=True)

In [86]:
data_ETH.head()

,open_time,open,high,low,close,volume,close_time,quote_volume,count,taker_buy_volume,taker_buy_quote_volume
10896,2019-09-01 00:00:00,171.52,172.89,171.36,172.45,5981.16399,2019-09-01 00:59:59.999,1.030126e+06,3753,3576.32332,615886.585686
10897,2019-09-01 01:00:00,172.47,173.42,172.41,172.71,7929.54701,2019-09-01 01:59:59.999,1.372183e+06,3310,5532.93656,957301.238661
10898,2019-09-01 02:00:00,172.67,172.97,172.02,172.43,2650.04457,2019-09-01 02:59:59.999,4.568114e+05,2666,1333.25886,229852.921103
10899,2019-09-01 03:00:00,172.41,172.83,172.32,172.57,2676.49085,2019-09-01 03:59:59.999,4.618308e+05,2612,1445.60395,249450.124375
10900,2019-09-01 04:00:00,172.50,172.74,172.11,172.46,2596.85893,2019-09-01 04:59:59.999,4.476401e+05,2848,1524.31952,262782.612091

In [87]:
data_ETH.tail()

,open_time,open,high,low,close,volume,close_time,quote_volume,count,taker_buy_volume,taker_buy_quote_volume
21921,2023-05-31 19:00:00,1864.00,1869.75,1861.62,1863.63,7481.4873,2023-05-31 19:59:59.999,1.395814e+07,12990,3109.6255,5.800020e+06
21922,2023-05-31 20:00:00,1863.63,1868.80,1863.20,1865.18,5792.0252,2023-05-31 20:59:59.999,1.080898e+07,14175,2874.1872,5.363770e+06
21923,2023-05-31 21:00:00,1865.17,1866.19,1861.48,1864.20,4703.4753,2023-05-31 21:59:59.999,8.767031e+06,10517,2218.9682,4.135989e+06
21924,2023-05-31 22:00:00,1864.19,1871.27,1863.72,1869.42,6868.3499,2023-05-31 22:59:59.999,1.282247e+07,10131,3404.9987,6.357285e+06
21925,2023-05-31 23:00:00,1869.43,1878.14,1868.11,1873.63,9750.8865,2023-05-31 23:59:59.999,1.826401e+07,13798,5141.8842,9.631578e+06

In [88]:
data_ETH.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32821 entries, 10896 to 21925
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   open_time               32821 non-null  datetime64[ns]
 1   open                    32821 non-null  float64
 2   high                    32821 non-null  float64
 3   low                     32821 non-null  float64
 4   close                   32821 non-null  float64
 5   volume                  32821 non-null  float64
 6   close_time              32821 non-null  datetime64[ns]
 7   quote_volume            32821 non-null  float64
 8   count                   32821 non-null  int64
 9   taker_buy_volume        32821 non-null  float64
 10  taker_buy_quote_volume  32821 non-null  float64
dtypes: datetime64[ns](2), float64(8), int64(1)
memory usage: 3.0 MB

In [89]:
# Saving ETH merged file

data_ETH.to_csv("/content/drive/MyDrive/Colab Notebooks/01 Omdena/Bahrain - Crypto/Project_Data/binance/ETHUSDT_merged.csv", index=False)

In [90]:
pd.read_csv("/content/drive/MyDrive/Colab Notebooks/01 Omdena/Bahrain - Crypto/Project_Data/binance/ETHUSDT_merged.csv")

,open_time,open,high,low,close,volume,close_time,quote_volume,count,taker_buy_volume,taker_buy_quote_volume
0,2019-09-01 00:00:00,171.52,172.89,171.36,172.45,5981.16399,2019-09-01 00:59:59.999,1.030126e+06,3753,3576.32332,6.158866e+05
1,2019-09-01 01:00:00,172.47,173.42,172.41,172.71,7929.54701,2019-09-01 01:59:59.999,1.372183e+06,3310,5532.93656,9.573012e+05
2,2019-09-01 02:00:00,172.67,172.97,172.02,172.43,2650.04457,2019-09-01 02:59:59.999,4.568114e+05,2666,1333.25886,2.298529e+05
3,2019-09-01 03:00:00,172.41,172.83,172.32,172.57,2676.49085,2019-09-01 03:59:59.999,4.618308e+05,2612,1445.60395,2.494501e+05
4,2019-09-01 04:00:00,172.50,172.74,172.11,172.46,2596.85893,2019-09-01 04:59:59.999,4.476401e+05,2848,1524.31952,2.627826e+05
...,...,...,...,...,...,...,...,...,...,...,...
32816,2023-05-31 19:00:00,1864.00,1869.75,1861.62,1863.63,7481.48730,2023-05-31 19:59:59.999,1.395814e+07,12990,3109.62550,5.800020e+06
32817,2023-05-31 20:00:00,1863.63,1868.80,1863.20,1865.18,5792.02520,2023-05-31 20:59:59.999,1.080898e+07,14175,2874.18720,5.363770e+06
32818,2023-05-31 21:00:00,1865.17,1866.19,1861.48,1864.20,4703.47530,2023-05-31 21:59:59.999,8.767031e+06,10517,2218.96820,4.135989e+06
32819,2023-05-31 22:00:00,1864.19,1871.27,1863.72,1869.42,6868.34990,2023-05-31 22:59:59.999,1.282247e+07,10131,3404.99870,6.357285e+06
32820,2023-05-31 23:00:00,1869.43,1878.14,1868.11,1873.63,9750.88650,2023-05-31 23:59:59.999,1.826401e+07,13798,5141.88420,9.631578e+06